trigger:
  - main

resources:
  repositories:
    - repository: manga-torremo-pipeline-azure
      endpoint: manganellidev
      type: github
      name: manganellidev/manga-torremo-pipeline-azure

extends:
  template: sdp-pipeline.yml@manga-torremo-pipeline-azure
  parameters:
    teamIdentifier: northstar
    appName: train
    artifactVersion: 1.2.334
    # ghRepoUri: https://github.com/manganellidev/ado-task-app

    skipRing0: false
    autoPromoteRing0: true
    targetRegionRing0: int
    bakeTimeInMinutesRing0: 1

    skipRing1: false
    autoPromoteRing1: false
    targetRegionRing1: eu
    bakeTimeInMinutesRing1: 1

    skipRing2: false
    autoPromoteRing2: true
    targetRegionRing2: us
    bakeTimeInMinutesRing2: 1

    skipRing3: false
    autoPromoteRing3: false
    targetRegionRing3: apj
