trigger:
  - main

resources:
  repositories:
    - repository: manga-torremo-pipeline-azure
      endpoint: manganellidev
      type: github
      name: manganellidev/manga-torremo-pipeline-azure

extends:
  template: sdp-pipeline.yml@manga-torremo-pipeline-azure
  parameters:
    teamIdentifier: northstar
    appName: train
    artifactVersion: 1.2.334

    rings:
      - targetRegion: "int"
        previousRegion: "none"
        autoPromote: true
        bakeTimeInMinutes: 1
        skipBakeTime: false
        skipPostDeployValidation: false
      - targetRegion: "eu"
        previousRegion: "int"
        autoPromote: true
        bakeTimeInMinutes: 1
        skipBakeTime: false
        skipPostDeployValidation: false
      - targetRegion: "us"
        previousRegion: "eu"
        autoPromote: true
        bakeTimeInMinutes: 1
        skipBakeTime: false
        skipPostDeployValidation: false
      - targetRegion: "apj"
        previousRegion: "us"
        autoPromote: true
        bakeTimeInMinutes: 1
        skipBakeTime: true
        skipPostDeployValidation: false
