trigger:
  - main

pool:
  name: Default

variables:
  SDP_GO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/sdp-go-lib-cache
  VERSION: 0.0.2

jobs:
  - job: Init
    displayName: "Init: Download and Cache Artifact"
    steps:
      - task: Cache@2
        inputs:
          key: '"concur-sdp-go-library-$(VERSION)" | "$(Agent.OS)"'
          path: "$(SDP_GO_LIB_CACHE_FOLDER)/"

      - task: JFrogGenericArtifacts@1
        inputs:
          command: "Download"
          connection: "artifactory_i851155"
          specSource: "taskConfiguration"
          fileSpec: |
            {
              "files": [
                {
                  "pattern": "concur-sdp-go-library/releases/concur-sdp-go-library-$(VERSION)",
                  "target": "$(SDP_GO_LIB_CACHE_FOLDER)/",
                  "flat": "true"
                }
              ]
            }
          failNoOp: true

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Listing contents of the default temp directory:"
            ls -la "$(SDP_GO_LIB_CACHE_FOLDER)/"

  - job: SDP
    dependsOn: Init
    displayName: "SDP: Call Go Library"
    steps:
      - task: Cache@2
        inputs:
          key: '"concur-sdp-go-library-$(VERSION)" | "$(Agent.OS)"'
          path: "$(SDP_GO_LIB_CACHE_FOLDER)/"

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Listing contents of tmp directory:"
            ls -la $(SDP_GO_LIB_CACHE_FOLDER)/

      - task: GetFolderContent@1.0.49
        displayName: "Get Folder Content 1.0.49"
        inputs:
          ParentFolder: "$(Pipeline.Workspace)/s"
