trigger:
  - main

pool:
  name: Default

steps:
  - script: echo Hello, world!
    displayName: "Run a one-line script"

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: "Run a multi-line script"

  # - script: |
  #     echo "Navigating to task directory"
  #     ls -la $(Agent.WorkFolder)
  #     ls -la $(Agent.WorkFolder)/_tasks
  #     cd $(Agent.WorkFolder)/_tasks/GetFolderContent_a80e0b20-314e-4460-8909-017c8e65ba45/1.0.30/
  #     cat package.json
  #     echo "Running npm install"
  #     npm install
  #   displayName: "Install Dependencies for GetFolderContent Task"

  - task: GetFolderContent@1.0.42
    displayName: "Get Folder Content 1.0.42"
    inputs:
      ParentFolder: "$(Pipeline.Workspace)/s"

  # - task: torremo@1
  #   displayName: Torremo
  #   inputs:
  #     stepName: "BakeTimeRing0"
  #     flags: "--verbose --force --dry-run"
  #     torremoVersion: "1.3.3"
