trigger:
  - main

resources:
  repositories:
    - repository: manga-torremo-pipeline-azure
      endpoint: manganellidev
      type: github
      name: manganellidev/manga-torremo-pipeline-azure

extends:
  template: sdp-pipeline.yml@manga-torremo-pipeline-azure
  parameters:
    teamIdentifier: northstar
    appName: train
    artifactVersion: 1.2.334

    # Ring 0
    skipRing0: false
    autoPromoteRing0: true
    dynatraceSmokeTestRing0: true
    targetRegionRing0: int
    bakeTimeInMinutesRing0: 1

    # Ring 1
    skipRing1: false
    autoPromoteRing1: true
    dynatraceSmokeTestRing1: true
    targetRegionRing1: eu
    bakeTimeInMinutesRing1: 1

    # Ring 2
    skipRing2: false
    autoPromoteRing2: true
    dynatraceSmokeTestRing2: true
    targetRegionRing2: us
    bakeTimeInMinutesRing2: 1

    # Ring 3
    skipRing3: false
    autoPromoteRing3: true
    dynatraceSmokeTestRing3: true
    targetRegionRing3: apj
