trigger:
  - main

# pool:
#   name: Default

variables:
  SDP_GO_LIB_CACHE_FOLDER: $(Pipeline.Workspace)/s/sdp-go-lib-cache
  VERSION: 0.0.1

jobs:
  - job: Init
    displayName: "Init: Download and Cache Artifact"
    steps:
      - task: Cache@2
        inputs:
          key: '"concur-sdp-go-library" | "$(Agent.OS)"'
          path: "$(SDP_GO_LIB_CACHE_FOLDER)/"

      - task: Bash@3
        displayName: "Download from GitHub Release"
        env:
          GITHUB_TOKEN: $(GH_TOKEN)
        inputs:
          targetType: "inline"
          script: |
            echo "Logging in to GitHub"
            gh auth login --hostname github.tools.sap --with-token <<< "$GITHUB_TOKEN"

            echo "Downloading release from GitHub"
            gh release download "$(VERSION)" \
              --repo concur-sap-ecosystem/sdp-go-library \
              --dir "$(SDP_GO_LIB_CACHE_FOLDER)"

      # - task: JFrogGenericArtifacts@1
      #   inputs:
      #     command: "Download"
      #     connection: "artifactory_i851155"
      #     specSource: "taskConfiguration"
      #     fileSpec: |
      #       {
      #         "files": [
      #           {
      #             "pattern": "concur-sdp-go-library/releases/concur-sdp-go-library-$(VERSION)",
      #             "target": "$(SDP_GO_LIB_CACHE_FOLDER)/",
      #             "flat": "true"
      #           }
      #         ]
      #       }
      #     failNoOp: true

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Listing contents of the default temp directory:"
            ls -la "$(SDP_GO_LIB_CACHE_FOLDER)/"

  - job: SDP
    dependsOn: Init
    displayName: "SDP: Call Go Library"
    steps:
      - task: Cache@2
        inputs:
          key: '"concur-sdp-go-library" | "$(Agent.OS)"'
          path: "$(SDP_GO_LIB_CACHE_FOLDER)/"

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: |
            echo "Listing contents of tmp directory:"
            ls -la $(SDP_GO_LIB_CACHE_FOLDER)/

      - task: GetFolderContent@1.0.53
        displayName: "Get Folder Content 1.0.53"
        inputs:
          ParentFolder: "$(Pipeline.Workspace)/s"

      - task: torremo@1.0.29
        displayName: Torremo
        inputs:
          stepName: "BakeTimeRing0"
          flags: "--verbose --force --dry-run"
          torremoVersion: "1.3.3"
