trigger:
  - main

resources:
  repositories:
    - repository: manga2-torremo-pipeline-azure
      endpoint: manganellidev
      type: github
      name: manganellidev/manga2-torremo-pipeline-azure

extends:
  template: sdp-pipeline.yml@manga2-torremo-pipeline-azure
  parameters:
    rings:
      - name: "ring_0"
        region: "eu"
        autoPromote: true
        bakeTimeInMinutes: 1
        dependsOn: ["init"]
      - name: "ring_1"
        region: "us"
        autoPromote: false
        bakeTimeInMinutes: 2
        dependsOn: ["ring_0"]
      - name: "ring_2"
        region: "apj"
        autoPromote: false
        bakeTimeInMinutes: 3
        dependsOn: ["ring_1"]
