env:
  targetLandscape: dev
sapId: i990099
image:
  repository: ado-task-app.common.az
  tag: 1.0.0
pod:
  port: 8080
service:
  type: ClusterIP
  port: 8082
resources:
  requests:
    memory: "20Mi"
    cpu: "0.05"
  limits:
    memory: "25Mi"
    cpu: "0.1"
